### ISSUE TITLE
Make printing config to console an option?

### ISSUE THREAD

**Issue by LRitesh** [stimulant/ampm#23]
Right now running ampm will print the config json to console. It's super useful while debugging but it'd be cool to make this an option so if the app goes down on a public display, the config details (which might have analytics email/password info in it) is not visible.

**Comment by endquote** [comment]
Good suggestion.

Another thing I do: On Windows, you probably have some shortcut to some batch file that starts the app. If you right-click the shortcut, get the properties, there's an option to start the console as minimized, so no one will see it.

**Comment by endquote** [comment]
Could also modify `fullConfig` to include an argument that tells it to remove any keys in the config called "password", but that's not really a full solution, maybe there's other stuff you want to hide, too.
https://github.com/stimulant/ampm/blob/master/model/consoleState.js#L58

I find it useful to spew the config to the console, there isn't any other way to know what config you're running with after the default/dev/live/machinename is merged, environment variables are swapped in, etc. 

Another thought could be to expose the config in the web console, but again you'd want to hide anything sensitive.

**Comment by richardeakin** [comment]
@endquote that's actually what we're currently doing (running the console window from a batch script as minimized), it is a decent solution however it lead to at least one ambiguity for us.  When the PC boots up in the morning, it downloads about 500mb-1gb of assets, and only afterwards does it run `ampm`.  There was a report that when the maintainer came in in the morning, the app wasn't running, I believe he just got there while the content was still be downloaded but I can't tell for sure. To him, it just looked like nothing was running because the command prompt was minimized.

@LRitesh has brought up the argument that you might not want the console window to be visible to users anyway, which I think is valid, however in our case the only person who will see it is a) someone who is there before the building is open or b) someone nearby when things go wrong, and they'll just see it for a second before the app pops back up.

> I find it useful to spew the config to the console, there isn't any other way to know what config you're running with after the default/dev/live/machinename is merged, environment variables are swapped in, etc.

Could printing out the current config selection achieve this in your case?

> Another thought could be to expose the config in the web console, but again you'd want to hide anything sensitive.

Longer-term, more access from the web console seems like a nice way to go, of course takes more work but that thing is so nice because you can easily access it from remote.

I would think a bool property like "printConfig" or "dumpConfig" would do the trick, which could default to true.

**Comment by endquote** [comment]
The thing to do is write the config to `$$serverState`, and then save it, which will mean it's written to `ampm-state.json`, which is getting created anyway. It won't actually be used for anything, but you could look there if you need to debug the config merging/parsing bits.

And then remove it from the console spew. I'll work on that.

**Comment by endquote** [comment]
Made the described change, reopen the issue if you don't like it.

**Comment by richardeakin** [comment]
I think this solution is quite nice (just ran it from latest `npm install`.
