### ISSUE TITLE
file name and line number for error logging

### ISSUE THREAD

**Issue by richardeakin** [stimulant/ampm#33]
We're using some code similar to the AMPMClient.cpp to send error messages to AMPM, however it seems like the file name and line number don't show up in the logs. Is this by design, or could it be made optional?

For now I'm just prepending the location info the the message string that send across, but wondering if I'm not meant to do that.

**Comment by endquote** [comment]
ampm won't know anything about your source code, so yes, you'd need to send it things like line numbers and file names. If AMPMClient.cpp could be changed such that it had an error method which automatically collected that info and sent it on to ampm, that would be most welcome.

The JavaScript client does send the stack trace and line numbers on errors, maybe you could do similar for c++.
https://github.com/stimulant/ampm/blob/master/samples/web/libs/ampm.js#L134

**Comment by richardeakin** [comment]
The current AMPMClient.cpp [sends through line and lineNum](https://github.com/stimulant/ampm/blob/dbfd8ee6d8ddeba182317e583a335d239724e516/samples/Cinder/Client/src/AMPMClient.cpp#L98-L101) to the server, but these are ignored by the server?

I'm happy just prepending the location data to the message, but looking at AMPMClient.cpp made me think this wasn't expected.

**Comment by endquote** [comment]
I looked into this. The log object is making it through to `_logMessage` here, but only the `.message` attribute ends up in the log file.

https://github.com/stimulant/ampm/blob/master/model/logging.js#L215

AMPMClient.cpp probably shouldn't construct a message object like that, because you'd reasonably assume something is happening with the other attributes... but it's not. A great PR would be to change it to examine the `level` to see if it's error, and if so, construct a string with all the info you want in it, which is what the JavaScript client does.

**Comment by richardeakin** [comment]
Okay, that makes sense to me. The file and line number already have to come from the client app, so we might as well bake it into the message on the client side (which is what I ended up doing).
